# Generated by Django 4.0.5 on 2022-07-20 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spitimage',
            name='spitz',
        ),
        migrations.DeleteModel(
            name='Spit',
        ),
        migrations.DeleteModel(
            name='SpitImage',
        ),
    ]
