# Generated by Django 4.0.5 on 2022-07-25 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Spit',
        ),
    ]
